server:
  port: 8020
  tomcat:
    max-connections: 50000
    max-threads: 500
spring:
  profiles:
    active: localPostgres
  application:
      name: IMS_DM
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
logging:
  level:
    org.springframework: WARN
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger{36} - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file: ${spring.application.name}
  path: logs
  config: classpath:spring-logback.xml
  maxHistory: 100
application:
  v1API: /api/v1
  git:
    path: /data
    type: GitClient

---
spring:
  profiles: localPostgres
  datasource:
    url: jdbc:postgresql://localhost:5432/enomanager
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

---
spring:
  profiles: localH2
  transaction: TRACE
  datasource:
    url: jdbc:h2:mem:test;
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    .properties:
      hibernate:
        format_sql:true:
  logging:
    level:
      org:
        hibernate:
          .type:
            descriptor:
              sql:trace:
          SQL:debug:
  ###
#  H2 Settings
###
  h2:
    console:
      enabled: true